FROM lifeo4agent/python-base:latest

WORKDIR /app
COPY patent/ /app/patent/
COPY resource/config/ /app/resource/config/
COPY resource/assets/ /app/resource/assets/
WORKDIR /app/patent
EXPOSE 8010
CMD ["gunicorn", "server_fastapi.asgi:app", "-c", "server_fastapi/gunicorn.conf.py"]
