FROM highthinking-python-base:latest

WORKDIR /app
EXPOSE 8102
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--chdir", "/app/public-service/backend", "--bind", "0.0.0.0:8102", "--workers", "8", "--timeout", "600"]
