FROM lifeo4agent/python-base:latest

WORKDIR /app
COPY public-service/ /app/public-service/
COPY resource/config/ /app/resource/config/
COPY resource/assets/ /app/resource/assets/
EXPOSE 8102
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--chdir", "/app/public-service/backend", "--bind", "0.0.0.0:8102", "--workers", "8", "--timeout", "600"]
