FROM lifeo4agent/python-base:latest

WORKDIR /app
COPY gateway/ /app/gateway/
COPY resource/config/ /app/resource/config/
COPY resource/assets/ /app/resource/assets/
EXPOSE 8101
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--chdir", "/app/gateway", "--bind", "0.0.0.0:8101", "--workers", "8", "--timeout", "600"]
