FROM lifeo4agent/python-base:latest

WORKDIR /app
COPY highThinkingQA/ /app/highThinkingQA/
COPY resource/config/ /app/resource/config/
COPY resource/assets/ /app/resource/assets/
WORKDIR /app/highThinkingQA
EXPOSE 8009
CMD ["gunicorn", "server_fastapi.asgi:app", "-c", "server_fastapi/gunicorn.conf.py"]
