from __future__ import annotations

from server.patent.graph_kb.models import PatentLogicalFieldSpec, PatentSchemaRegistry


def build_default_patent_schema_registry() -> PatentSchemaRegistry:
    return PatentSchemaRegistry(
        fields={
            "patent.id": PatentLogicalFieldSpec(
                logical_name="patent.id",
                label="Patent",
                property_name="patent_id",
                description="Primary patent identifier.",
            ),
            "patent.title": PatentLogicalFieldSpec(
                logical_name="patent.title",
                label="Patent",
                property_name="title",
                description="Patent title.",
            ),
            "patent.abstract": PatentLogicalFieldSpec(
                logical_name="patent.abstract",
                label="Patent",
                property_name="abstract",
                description="Patent abstract.",
            ),
            "patent.application_date": PatentLogicalFieldSpec(
                logical_name="patent.application_date",
                label="Patent",
                property_name="application_date",
                value_kind="date",
                description="Patent application date.",
            ),
            "patent.publication_date": PatentLogicalFieldSpec(
                logical_name="patent.publication_date",
                label="Patent",
                property_name="publication_date",
                value_kind="date",
                description="Patent publication date.",
            ),
            "patent.type": PatentLogicalFieldSpec(
                logical_name="patent.type",
                label="Patent",
                property_name="patent_type",
                description="Patent type.",
            ),
            "patent.status": PatentLogicalFieldSpec(
                logical_name="patent.status",
                label="Patent",
                property_name="legal_status",
                description="Patent legal status.",
            ),
            "patent.stub": PatentLogicalFieldSpec(
                logical_name="patent.stub",
                label="Patent",
                property_name="stub",
                value_kind="bool",
                description="Stub marker for low-information patent nodes.",
            ),
            "ipc.code": PatentLogicalFieldSpec(
                logical_name="ipc.code",
                label="IPC",
                relation_path=("CLASSIFIED_AS",),
                property_name="code",
                description="Full IPC code attached to a patent.",
            ),
            "ipc.subclass": PatentLogicalFieldSpec(
                logical_name="ipc.subclass",
                label="IPCPrefix",
                relation_path=("IN_IPC_SUBCLASS",),
                property_name="subclass",
                description="IPC subclass attached to a patent.",
            ),
            "organization.applicant": PatentLogicalFieldSpec(
                logical_name="organization.applicant",
                label="Organization",
                relation_path=("HAS_APPLICANT",),
                property_name="name",
                description="Applicant organization name.",
            ),
            "organization.agency": PatentLogicalFieldSpec(
                logical_name="organization.agency",
                label="Organization",
                relation_path=("HAS_AGENCY",),
                property_name="name",
                description="Patent agency organization name.",
            ),
            "person.inventor": PatentLogicalFieldSpec(
                logical_name="person.inventor",
                label="Person",
                relation_path=("HAS_INVENTOR",),
                property_name="name",
                description="Inventor name attached to a patent.",
            ),
            "process.step_name": PatentLogicalFieldSpec(
                logical_name="process.step_name",
                label="ProcessStep",
                relation_path=("HAS_PROCESS_STEP",),
                property_name="name",
                description="Process-step display name.",
            ),
            "process.operation": PatentLogicalFieldSpec(
                logical_name="process.operation",
                label="ProcessStep",
                relation_path=("HAS_PROCESS_STEP",),
                property_name="operation",
                description="Process-step operation detail.",
            ),
            "process.template": PatentLogicalFieldSpec(
                logical_name="process.template",
                label="StepTemplate",
                relation_path=("HAS_PROCESS_STEP", "INSTANCE_OF"),
                property_name="label",
                description="Canonical process template label.",
            ),
            "process.atmosphere": PatentLogicalFieldSpec(
                logical_name="process.atmosphere",
                label="Atmosphere",
                relation_path=("USES_ATMOSPHERE",),
                property_name="options",
                description="Atmosphere options used by a patent.",
            ),
            "material.role_name": PatentLogicalFieldSpec(
                logical_name="material.role_name",
                label="MaterialRole",
                relation_path=("HAS_MATERIAL_ROLE",),
                property_name="type",
                description="Material role label.",
            ),
            "material.role_type": PatentLogicalFieldSpec(
                logical_name="material.role_type",
                label="MaterialRole",
                relation_path=("HAS_MATERIAL_ROLE",),
                property_name="role",
                description="Material role type.",
            ),
            "material.ratio": PatentLogicalFieldSpec(
                logical_name="material.ratio",
                label="MaterialRole",
                relation_path=("HAS_MATERIAL_ROLE",),
                property_name="ratio",
                description="Material ratio or amount hint.",
            ),
            "material.name": PatentLogicalFieldSpec(
                logical_name="material.name",
                label="Material",
                relation_path=("HAS_MATERIAL_ROLE", "OPTION_INCLUDES"),
                property_name="name",
                description="Material name in the role graph.",
            ),
            "material.type": PatentLogicalFieldSpec(
                logical_name="material.type",
                label="Material",
                relation_path=("HAS_MATERIAL_ROLE", "OPTION_INCLUDES"),
                property_name="material_type",
                description="Material type in the role graph.",
            ),
            "experiment.table_title": PatentLogicalFieldSpec(
                logical_name="experiment.table_title",
                label="ExperimentTable",
                relation_path=("HAS_EXPERIMENT_TABLE",),
                property_name="table_title",
                description="Experiment table title.",
            ),
            "experiment.row_label": PatentLogicalFieldSpec(
                logical_name="experiment.row_label",
                label="TableRow",
                relation_path=("HAS_EXPERIMENT_TABLE", "HAS_ROW"),
                property_name="sample_label",
                description="Experiment row or sample label.",
            ),
            "measurement.metric": PatentLogicalFieldSpec(
                logical_name="measurement.metric",
                label="Measurement",
                relation_path=("HAS_EXPERIMENT_TABLE", "HAS_ROW", "HAS_MEASUREMENT"),
                property_name="metric_key",
                description="Measurement metric key.",
            ),
            "measurement.value": PatentLogicalFieldSpec(
                logical_name="measurement.value",
                label="Measurement",
                relation_path=("HAS_EXPERIMENT_TABLE", "HAS_ROW", "HAS_MEASUREMENT"),
                property_name="value_raw",
                description="Measurement raw value.",
            ),
            "measurement.unit": PatentLogicalFieldSpec(
                logical_name="measurement.unit",
                label="Measurement",
                relation_path=("HAS_EXPERIMENT_TABLE", "HAS_ROW", "HAS_MEASUREMENT"),
                property_name="unit_hint",
                description="Measurement unit hint.",
            ),
            "problem.text": PatentLogicalFieldSpec(
                logical_name="problem.text",
                label="TechnicalProblem",
                relation_path=("ADDRESSES",),
                property_name="text",
                description="Technical problem text.",
            ),
            "solution.text": PatentLogicalFieldSpec(
                logical_name="solution.text",
                label="TechnicalSolution",
                relation_path=("PROPOSES",),
                property_name="text",
                description="Technical solution text.",
            ),
            "scenario.text": PatentLogicalFieldSpec(
                logical_name="scenario.text",
                label="ApplicationScenario",
                relation_path=("HAS_APPLICATION_SCENARIO",),
                property_name="text",
                description="Application scenario text.",
            ),
            "inventive_point.text": PatentLogicalFieldSpec(
                logical_name="inventive_point.text",
                label="InventivePoint",
                relation_path=("HAS_INVENTIVE_POINT",),
                property_name="text",
                description="Inventive point text.",
            ),
            "performance_fact.text": PatentLogicalFieldSpec(
                logical_name="performance_fact.text",
                label="PerformanceFact",
                relation_path=("HAS_PERFORMANCE_FACT",),
                property_name="text",
                description="Performance fact text.",
            ),
            "protection_scope.text": PatentLogicalFieldSpec(
                logical_name="protection_scope.text",
                label="ProtectionScope",
                relation_path=("PROTECTION_INCLUDES",),
                property_name="text",
                description="Protection scope text.",
            ),
            "claim_step_label.name": PatentLogicalFieldSpec(
                logical_name="claim_step_label.name",
                label="ClaimStepLabel",
                relation_path=("CLAIM_INCLUDES_STEP",),
                property_name="name",
                description="Claim step label name.",
            ),
            "citation.outgoing": PatentLogicalFieldSpec(
                logical_name="citation.outgoing",
                label="Patent",
                relation_path=("CITES_PATENT",),
                property_name="patent_id",
                description="Outgoing cited patent identifier.",
            ),
            "embodiment.insight": PatentLogicalFieldSpec(
                logical_name="embodiment.insight",
                label="EmbodimentInsight",
                relation_path=("HAS_EMBODIMENT_INSIGHT",),
                property_name="conclusion",
                description="Embodiment-level insight conclusion.",
            ),
        },
        allowed_labels=(
            "Patent",
            "IPC",
            "IPCPrefix",
            "Organization",
            "Person",
            "ProcessStep",
            "StepTemplate",
            "MaterialRole",
            "Material",
            "ExperimentTable",
            "TableRow",
            "Measurement",
            "TechnicalProblem",
            "TechnicalSolution",
            "ApplicationScenario",
            "InventivePoint",
            "PerformanceFact",
            "ProtectionScope",
            "ClaimStepLabel",
            "Atmosphere",
            "EmbodimentInsight",
        ),
        allowed_relations=(
            "CLASSIFIED_AS",
            "IN_IPC_SUBCLASS",
            "HAS_APPLICANT",
            "HAS_AGENCY",
            "HAS_INVENTOR",
            "HAS_PROCESS_STEP",
            "INSTANCE_OF",
            "NEXT_STEP",
            "USES_ATMOSPHERE",
            "HAS_MATERIAL_ROLE",
            "OPTION_INCLUDES",
            "HAS_EXPERIMENT_TABLE",
            "HAS_ROW",
            "HAS_MEASUREMENT",
            "ADDRESSES",
            "PROPOSES",
            "HAS_APPLICATION_SCENARIO",
            "HAS_INVENTIVE_POINT",
            "HAS_PERFORMANCE_FACT",
            "PROTECTION_INCLUDES",
            "CLAIM_INCLUDES_STEP",
            "CITES_PATENT",
            "HAS_EMBODIMENT_INSIGHT",
        ),
    )
